from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):

    def setupUi(self, Form, colour, colourb):
        try:
            if self.wr1:
                Form.setStyleSheet("background-color: rgb{};".format(colour))
                self.save.setStyleSheet(
                    "background-color: rgb{};".format(colourb))
                self.use_settings.setStyleSheet(
                    "background-color: rgb{};".format(colourb))


        except Exception:
            Form.setObjectName("Form")
            Form.resize(371, 380)
            Form.setStyleSheet("background-color: rgb{};".format(colour))
            self.save = QtWidgets.QPushButton(Form)
            self.save.setGeometry(QtCore.QRect(10, 320, 351, 51))
            self.save.setStyleSheet("background-color: rgb{};".format(colourb))
            self.save.setObjectName("save")
            self.verticalLayoutWidget = QtWidgets.QWidget(Form)
            self.verticalLayoutWidget.setGeometry(
                QtCore.QRect(10, 40, 160, 226))
            self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
            self.background_color = QtWidgets.QVBoxLayout(
                self.verticalLayoutWidget)
            self.background_color.setContentsMargins(0, 0, 0, 0)
            self.background_color.setObjectName("background_color")
            self.color_1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
            self.color_1.setObjectName("color_1")
            self.background_color.addWidget(self.color_1)
            self.color_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
            self.color_2.setObjectName("color_2")
            self.background_color.addWidget(self.color_2)
            self.color_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
            self.color_3.setObjectName("color_3")
            self.background_color.addWidget(self.color_3)
            self.color_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
            self.color_5.setObjectName("color_5")
            self.background_color.addWidget(self.color_5)
            self.color_6 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
            self.color_6.setObjectName("color_6")
            self.background_color.addWidget(self.color_6)
            self.color_7 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
            self.color_7.setObjectName("color_7")
            self.background_color.addWidget(self.color_7)
            self.color_8 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
            self.color_8.setObjectName("color_8")
            self.background_color.addWidget(self.color_8)
            self.color_9 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
            self.color_9.setObjectName("color_9")
            self.background_color.addWidget(self.color_9)
            self.color_10 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
            self.color_10.setObjectName("color_10")
            self.background_color.addWidget(self.color_10)
            self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
            self.verticalLayoutWidget_2.setGeometry(
                QtCore.QRect(190, 40, 160, 221))
            self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
            self.buttons_color = QtWidgets.QVBoxLayout(
                self.verticalLayoutWidget_2)
            self.buttons_color.setContentsMargins(0, 0, 0, 0)
            self.buttons_color.setObjectName("buttons_color")
            self.color2_1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
            self.color2_1.setObjectName("color2_1")
            self.buttons_color.addWidget(self.color2_1)
            self.color2_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
            self.color2_2.setObjectName("color2_2")
            self.buttons_color.addWidget(self.color2_2)
            self.color2_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
            self.color2_3.setObjectName("color2_3")
            self.buttons_color.addWidget(self.color2_3)
            self.color2_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
            self.color2_4.setObjectName("color2_4")
            self.buttons_color.addWidget(self.color2_4)
            self.color2_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
            self.color2_5.setObjectName("color2_5")
            self.buttons_color.addWidget(self.color2_5)
            self.color2_6 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
            self.color2_6.setObjectName("color2_6")
            self.buttons_color.addWidget(self.color2_6)
            self.color2_7 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
            self.color2_7.setObjectName("color2_7")
            self.buttons_color.addWidget(self.color2_7)
            self.color2_8 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
            self.color2_8.setObjectName("color2_8")
            self.buttons_color.addWidget(self.color2_8)
            self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
            self.horizontalLayoutWidget.setGeometry(
                QtCore.QRect(10, 10, 351, 21))
            self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
            self.horizontalLayout = QtWidgets.QHBoxLayout(
                self.horizontalLayoutWidget)
            self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout.setObjectName("horizontalLayout")
            self.wr2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
            self.wr2.setObjectName("wr2")
            self.horizontalLayout.addWidget(self.wr2)
            self.wr1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
            self.wr1.setObjectName("wr1")
            self.horizontalLayout.addWidget(self.wr1)

            self.use_settings = QtWidgets.QPushButton(Form)
            self.use_settings.setGeometry(QtCore.QRect(190, 270, 171, 31))
            self.use_settings.setStyleSheet(
                "background-color: rgb{};".format(colourb))
            self.use_settings.setObjectName("use_settings")

            self.retranslateUi(Form)
            QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Settings"))
        self.save.setText(_translate("Form", "Сохранить данные о кинотеатрах"))
        self.color_1.setText(_translate("Form", "Белый"))
        self.color_2.setText(_translate("Form", "Светло-серый"))
        self.color_3.setText(_translate("Form", "Тёмно-сер"))
        self.color_5.setText(_translate("Form", "Фиолетовый"))
        self.color_6.setText(_translate("Form", "Персик"))
        self.color_7.setText(_translate("Form", "Светло-розовый"))
        self.color_8.setText(_translate("Form", "Фисташковый"))
        self.color_9.setText(_translate("Form", "Зеленый"))
        self.color_10.setText(_translate("Form", "Бирюзовый"))
        self.color2_1.setText(_translate("Form", "Белый"))
        self.color2_2.setText(_translate("Form", "Светло-серый"))
        self.color2_3.setText(_translate("Form", "Фиолетовый"))
        self.color2_4.setText(_translate("Form", "Пэрсик"))
        self.color2_5.setText(_translate("Form", "Светло-розовый"))
        self.color2_6.setText(_translate("Form", "Фисташковый"))
        self.color2_7.setText(_translate("Form", "Зеленый"))
        self.color2_8.setText(_translate("Form", "Бирюзовый"))
        self.wr2.setText(_translate("Form", "Цвет фона:"))
        self.wr1.setText(_translate("Form", "Цвет кнопок:"))
        self.use_settings.setText(
            _translate("Form", "Применить настройки цвета"))
